# CAR Evaluation KNN Classifier

In [1]:
import pandas as pd
import numpy as np

In [2]:
## Load dataset - data is categorical
clist=['buying','maint', 'doors', 'persons', 'lug_boot', 'safety', 'carclass']
df = pd.read_csv("uci-car-evaluation/original/car_data.csv", names=clist)
df.shape
df.head


<bound method NDFrame.head of      buying  maint  doors persons lug_boot safety carclass
0     vhigh  vhigh      2       2    small    low    unacc
1     vhigh  vhigh      2       2    small    med    unacc
2     vhigh  vhigh      2       2    small   high    unacc
3     vhigh  vhigh      2       2      med    low    unacc
4     vhigh  vhigh      2       2      med    med    unacc
...     ...    ...    ...     ...      ...    ...      ...
1723    low    low  5more    more      med    med     good
1724    low    low  5more    more      med   high    vgood
1725    low    low  5more    more      big    low    unacc
1726    low    low  5more    more      big    med     good
1727    low    low  5more    more      big   high    vgood

[1728 rows x 7 columns]>

In [3]:
df.head()

buying  maint doors persons lug_boot safety carclass
0  vhigh  vhigh     2       2    small    low    unacc
1  vhigh  vhigh     2       2    small    med    unacc
2  vhigh  vhigh     2       2    small   high    unacc
3  vhigh  vhigh     2       2      med    low    unacc
4  vhigh  vhigh     2       2      med    med    unacc

In [4]:
df['buying'].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [5]:
df['maint'].unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [6]:
df['doors'].unique()

array(['2', '3', '4', '5more'], dtype=object)

In [7]:
df['persons'].unique()

array(['2', '4', 'more'], dtype=object)

In [8]:
df['lug_boot'].unique()

array(['small', 'med', 'big'], dtype=object)

In [9]:
df['safety'].unique()

array(['low', 'med', 'high'], dtype=object)

In [10]:
df['carclass'].unique()

array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [11]:
buy = {'vhigh':0, 'high':1, 'med':2, 'low':3}
df['buying'] = df['buying'].map(lambda x: buy[x])

In [12]:
m = {'vhigh':0, 'high':1, 'med':2, 'low':3}
df['maint'] = df['maint'].map(lambda x: m[x])

In [13]:
d={'2':0, '3':1, '4':2, '5more':3}
df['doors']=df['doors'].map(lambda x: d[x])

In [14]:
p={'2':0, '4':1, 'more':2}
df['persons']=df['persons'].map(lambda x: p[x])

In [15]:
lb={'small':0, 'med':1, 'big':2}
df['lug_boot']=df['lug_boot'].map(lambda x: lb[x])

In [16]:
sf={'low':0, 'med':1, 'high':2}
df['safety']=df['safety'].map(lambda x: sf[x])

In [17]:
crcl={'unacc':0, 'acc':1, 'vgood':2, 'good':3}
df['carclass']=df['carclass'].map(lambda x: crcl[x])

In [18]:
from sklearn import neighbors
classifier_knc= neighbors.KNeighborsClassifier()

# Seperate independe
x=df.iloc[:,:6]
y=df.iloc[:,6]

from sklearn import model_selection
from sklearn.model_selection import train_test_split

test_size=0.3
seed=7
x_train, x_test, y_train, y_test=model_selection.train_test_split(x,y,test_size=test_size,random_state=seed)
classifier_knc.fit(x_train,y_train)
predicted=classifier_knc.predict(x_test)
print("Predicted:",predicted)
print("Actual:",y_test)

Predicted: [0 0 0 0 0 1 0 1 0 0 0 0 3 0 1 0 0 3 0 1 0 0 0 2 0 0 0 0 3 0 0 0 1 0 0 0 2
 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 0 3 1 0
 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 1 1 0 0 0 1 3 0 1 1 0 2 0 1 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 2 1 0 0 0
 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 2 1 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0
 1 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 3 0 2 0 0 0
 0 2 0 0 2 0 0 0 0 0 2 0 0 1 0 0 0 2 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1
 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 0 0
 0 1 0 0 3 1 0 0 0 1 0 0 0 0 1 1 0 0 0 3 0 1 0 1 0 0 1 1 0 0 0 2 0 0 1 2 0
 0 0 0 3 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0
 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0
 2 2 0 0 2 1 2

## Test Accuracy

In [19]:
# Test Classification accuracy
from sklearn.metrics import accuracy_score
a_socre=accuracy_score(y_test,predicted)
print(a_socre)

0.9171483622350675


## Confusion Matrix

In [20]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
matrix=confusion_matrix(y_test, predicted)
print(matrix)

[[362   1   0   0]
 [ 23  89   0   0]
 [  1   6  18   2]
 [  2   7   1   7]]


## Class Report

In [21]:
from sklearn.metrics import classification_report
class_report=classification_report(y_test,predicted)
print(class_report)

              precision    recall  f1-score   support

           0       0.93      1.00      0.96       363
           1       0.86      0.79      0.83       112
           2       0.95      0.67      0.78        27
           3       0.78      0.41      0.54        17

    accuracy                           0.92       519
   macro avg       0.88      0.72      0.78       519
weighted avg       0.91      0.92      0.91       519

